### ISSUE TITLE
502 Bad Gateway

### ISSUE THREAD

**Issue by JayPerfetto** [bendl/node-xbox#2]
I have been getting 502s when hitting multiple endpoints - I also get a 502 response when trying to go to the XboxAPI website. Any advice?

Jason

**Comment by JayPerfetto** [comment]
Bump ^

**Comment by bendl** [comment]
I believe this is a problem on xboxapi.com's side - I'm getting 502s when trying to login (https://xboxapi.com/login).
There's not much node-xbox can do about it since it gets data straight from xboxapi.com.

Of course, it would be better to get data directly from Xbox, but I haven't been active on Xbox/node-xbox in years and so don't have/know of a fix/alternative.

**Comment by JayPerfetto** [comment]
No worries - thanks for the follow up - FWIW your package works great still and the 502s are def an Xbox api.com issue
